### PR TITLE
Initial sphinx docs

### LINKED ISSUE #98: doctests for examples
Implement doctests for examples in readme. Probably should just set a proper sphinx doc subtree before this.

### PR DESCRIPTION
**Pull request by goodboy**
Get some sphinx docs going and this should mostly resolve #98 and #108.

Should probably just do the same with all the remaining examples in the docs too I guess eh?

### CODE REVIEW

**Comment by goodboy** [comment]
Initial draft preview [available on RTD here](https://tractor.readthedocs.io/en/init_sphinx_docs/)!

**Comment by goodboy** [comment]
@dxflores this should also entirely resolve #108 for you.

Please let me know if there are any further problems!

**Comment by goodboy** [comment]
If we can get someone else to say the docs look aight then I'll gladly merge this and we should be more on our way towards #104

**Comment by dxflores** [comment]
All examples worked.

**Comment by goodboy** [comment]
@dxflores nice! Alright landing this then!
If there's any quiffs with the docs themselves we'll take it up in in new issues and PRs.

**Comment by goodboy** [comment]
Sweet, [they're live](https://tractor.readthedocs.io/en/latest/).

**Pull request merged**
