### PR TITLE
Remove asyncio from TODOs

### LINKED ISSUE #286: Drop `asyncio` mode from readme ToDo
I forgot to [remove it](https://github.com/goodboy/tractor#whats-on-the-todo) since it's on the features list now.

### PR DESCRIPTION
**Pull request by houtenjack**
Fixes #286

I suppose there is no need for more documentation, given [this section on the README](https://github.com/goodboy/tractor/blob/master/docs/README.rst#infected-asyncio-mode)

### CODE REVIEW

**Comment by goodboy** [comment]
🤩 

@houtenjack, do you think you could add a small snippet to the [features list?](https://github.com/goodboy/tractor/blob/master/docs/README.rst#features)

**Comment by houtenjack** [comment]
Sorry for the delay, isn't the snipper already [in the README](https://github.com/goodboy/tractor/blob/master/docs/README.rst#infected-asyncio-mode)?

**Comment by goodboy** [comment]
@houtenjack yes. I'm asking about putting a summary bullet in the [features list](https://github.com/goodboy/tractor/blob/master/docs/README.rst#features) at the top.

**Comment by houtenjack** [comment]
I added a new bullet point, I'm not sure what the difference with the previous one in the list would be though.

**Comment by goodboy** [comment]
@houtenjack 🤦🏼 i didn't realize there already was one?

Ye sorry I'm a dum dum.
Disregard, the original patch you had was correct 😂

**Comment by houtenjack** [comment]
No worries!
I pushed a revert!

**Pull request merged**
